apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rr8z0jdo9-go 
  janus-idp.io/tekton: rr8z0jdo9-go
  backstage.io/kubernetes-id: rr8z0jdo9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rr8z0jdo9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml