apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rr8z0jdo9-go
  janus-idp.io/tekton: rr8z0jdo9-go
  backstage.io/kubernetes-id: rr8z0jdo9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rr8z0jdo9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
